### ISSUE TITLE
Avoid using LinkedList.get(int) because it causes performance issues

### ISSUE THREAD

**Issue by AlexisJehan** [AxelAmbert/MarkovChainsMetropolis#1]
Use ArrayList instead for that.

Keep going with Java.

**Comment by JSCharlot** [comment]
ArrayList should not be used in every scenarios.
According to this article, ArrayList should be used to store/access datas and LinkedList to manipulate datas : 
https://www.javatpoint.com/difference-between-arraylist-and-linkedlist

**Comment by AxelAmbert** [comment]
Dear Alexis and Jean-Sebastien,

I may disagree on you with this point.
As you may know Markov Chain tend to grow nodes in certain situations (mostly Continuous Time Markov Chain) so I leave the user of thoses class the free will to change its implementation.
Even tho it's right that in the Simulation class, no new node is added.
